name: Check Dockerfile with hadolint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-latest
    container:
      image: hadolint/hadolint:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Check code with Hadolint
        run: hadolint Dockerfile