name: Check Dockerfile with hadolint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Check code with Hadolint
        uses: jbergstroem/hadolint-gh-action@v1
